version: '3.5'
services:
    api-db:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_db_data:/var/lib/postgresql/data
        env_file:
            - ./env

    api:
        build:
            context: api
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            - ./env
        volumes:
            - ./api:/app
        depends_on:
            - api-db
        network_mode: host

    frontend:
        build:
            context: client
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - api