name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs: 
  client:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup Client
        working-directory: client
        run: |
          yarn install
          yarn global add eslint
          yarn add eslint-plugin-vue
          
      - name: Run Client Tests
        working-directory: client
        run: yarn test:unit:ci
          
      - name: Run Client Lint
        working-directory: client
        run: yarn lint
          
  api:
    runs-on: ubuntu-latest
    services:
      api-db:
        image: postgres
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myproject
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install API Requirements
        working-directory: api
        run: pip install -r requirements.txt
        
      - name: Run API Migrations
        working-directory: api
        run: python manage.py migrate
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myproject
          POSTGRES_PORT: 5432
          
      - name: Run API Tests
        working-directory: api
        run: |
          coverage run manage.py test
          coverage report --fail-under=90

      - name: Run API Lint
        working-directory: api
        run: pylint --load-plugins pylint_django *.py --fail-under=4
          
  code_quality:
    runs-on: ubuntu-latest

    steps:
        - name: Run Code Inspector
          uses: codeinspectorio/github-action@v1
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
            code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
            min_quality_grade: 'GOOD'
            min_quality_score: '80'
            max_long_functions_rate: '1'
            max_defects_rate: '1'
