name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup Client
        working-directory: client
        run: |
          yarn install
          yarn global add eslint
          yarn add eslint-plugin-vue
          
      - name: Run Client Tests
        working-directory: client
        run: yarn test:unit:ci
          
      - name: Run Client Lint
        working-directory: client
        run: yarn lint
        
      - uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: client
          args: >
            -Dsonar.projectKey=SamButers_Trabalho-Individual-2020-2
            -Dsonar.organization=sambuters
          
  api:
    runs-on: ubuntu-latest
    
    steps:
    - name: To be implemented
      run: echo To be implemented.
      
