name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Run Client Tests
        working-directory: client
        run: |
          yarn install
          yarn test:unit:ci
          
  api:
    runs-on: ubuntu-latest
    
    steps:
    - name: To be implemented
      run: echo To be implemented.
      
